START TRANSACTION;

CREATE TABLE IF NOT EXISTS meme_coins (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    popularity_score INT UNSIGNED NOT NULL DEFAULT 0
);

-- 需要的話可以加入 index

COMMIT;